proxy:
  port: 8082
  realm: httprox
  secured: true

## [MITM]
MITM:
  enabled: true
  ca:
    key: /tmp/ssl/ca.der
    cert: /tmp/ssl/ca.crt
  dn:
    template: CN=<host>, O=Test Org
  so:
    timeout:
      minutes: 30

tracking:
  type: SUFFIX

## [rest client]
content-retrieval-service-api/mp-rest/uri: http://indy.url
content-retrieval-service-api/mp-rest/scope: javax.inject.Singleton

repo-service-api/mp-rest/uri: http://indy.url
repo-service-api/mp-rest/scope: javax.inject.Singleton

## [auth]
auth:
  enabled: false
  realm: keycloak.realm
  public-key: keycloak.realmPublicKey
  keycloak-json: keycloak/keycloak.json
  keycloak-ui-json: keycloak/keycloak-ui.json
  security-bindings-json: keycloak/security-bindings.json
  url: keycloak.url
  server:
    credential:
      secret: keycloak.serverCredentialSecret
    resource: indy
  ui:
    resource: indy-ui




